///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace TeamCity_Automation.Desktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AddUser recording.
    /// </summary>
    [TestModule("4e8455a9-223b-47f6-9885-ea6e9ab3e78b", ModuleType.Recording, 1)]
    public partial class AddUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the TeamCity_Automation.TeamCity_AutomationRepository repository.
        /// </summary>
        public static TeamCity_Automation.TeamCity_AutomationRepository repo = TeamCity_Automation.TeamCity_AutomationRepository.Instance;

        static AddUser instance = new AddUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AddUser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AddUser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Desktop.FirstName' at 25;9.", repo.Desktop.FirstNameInfo, new RecordItemIndex(0));
            repo.Desktop.FirstName.Click("25;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Jay' with focus on 'Desktop.FirstName'.", repo.Desktop.FirstNameInfo, new RecordItemIndex(1));
            repo.Desktop.FirstName.PressKeys("Jay");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Desktop.LastName' at 12;6.", repo.Desktop.LastNameInfo, new RecordItemIndex(2));
            repo.Desktop.LastName.Click("12;6");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Branham' with focus on 'Desktop.LastName'.", repo.Desktop.LastNameInfo, new RecordItemIndex(3));
            repo.Desktop.LastName.PressKeys("Branham");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Desktop.Movie' at 20;3.", repo.Desktop.MovieInfo, new RecordItemIndex(4));
            repo.Desktop.Movie.Click("20;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Desktop.RbMale' at 7;10.", repo.Desktop.RbMaleInfo, new RecordItemIndex(5));
            repo.Desktop.RbMale.Click("7;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Desktop.BtAdd' at 30;9.", repo.Desktop.BtAddInfo, new RecordItemIndex(6));
            repo.Desktop.BtAdd.Click("30;9");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
