///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TeamCity_Automation
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TeamCity_AutomationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("829f5598-ff9a-4dd5-a51f-d1ff973eaa22")]
    public partial class TeamCity_AutomationRepository : RepoGenBaseFolder
    {
        static TeamCity_AutomationRepository instance = new TeamCity_AutomationRepository();
        TeamCity_AutomationRepositoryFolders.DesktopAppFolder _desktop;
        TeamCity_AutomationRepositoryFolders.WebAppFolder _web;

        /// <summary>
        /// Gets the singleton class instance representing the TeamCity_AutomationRepository element repository.
        /// </summary>
        [RepositoryFolder("829f5598-ff9a-4dd5-a51f-d1ff973eaa22")]
        public static TeamCity_AutomationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TeamCity_AutomationRepository() 
            : base("TeamCity_AutomationRepository", "/", null, 0, false, "829f5598-ff9a-4dd5-a51f-d1ff973eaa22", ".\\RepositoryImages\\TeamCity_AutomationRepository829f5598.rximgres")
        {
            _desktop = new TeamCity_AutomationRepositoryFolders.DesktopAppFolder(this);
            _web = new TeamCity_AutomationRepositoryFolders.WebAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("829f5598-ff9a-4dd5-a51f-d1ff973eaa22")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Desktop folder.
        /// </summary>
        [RepositoryFolder("5039aaa8-a26d-47b2-b743-107b3893977d")]
        public virtual TeamCity_AutomationRepositoryFolders.DesktopAppFolder Desktop
        {
            get { return _desktop; }
        }

        /// <summary>
        /// The Web folder.
        /// </summary>
        [RepositoryFolder("919c0d2e-fa35-4b4d-9ff7-f984312e6d17")]
        public virtual TeamCity_AutomationRepositoryFolders.WebAppFolder Web
        {
            get { return _web; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class TeamCity_AutomationRepositoryFolders
    {
        /// <summary>
        /// The DesktopAppFolder folder.
        /// </summary>
        [RepositoryFolder("5039aaa8-a26d-47b2-b743-107b3893977d")]
        public partial class DesktopAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _vipcount1Info;

            /// <summary>
            /// Creates a new Desktop  folder.
            /// </summary>
            public DesktopAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Desktop", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "5039aaa8-a26d-47b2-b743-107b3893977d", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "?/?/text[@accessiblename='First Name:']", 30000, null, "6984b63c-e25e-4a2e-924e-843da336f2de");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 30000, null, "f93e1261-e3b3-443d-bbaa-611fffbc3254");
                _movieInfo = new RepoItemInfo(this, "Movie", "list[@controlname='lbCategory']/?/?/listitem[@accessiblename='Movie']", 30000, null, "43b6a3c7-5752-4e44-acbc-4226c2829a50");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 30000, null, "10e68b95-b254-41da-9a47-f7795a3d2b27");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 30000, null, "eeefab4f-f174-4d9a-a4ff-8c986fd4d76c");
                _vipcount1Info = new RepoItemInfo(this, "VIPCount1", "?/?/text[@accessiblename='VIP count: 1']", 30000, null, "bd2622ff-ad47-4aab-b914-88cab0848f16");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5039aaa8-a26d-47b2-b743-107b3893977d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5039aaa8-a26d-47b2-b743-107b3893977d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("6984b63c-e25e-4a2e-924e-843da336f2de")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("6984b63c-e25e-4a2e-924e-843da336f2de")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("f93e1261-e3b3-443d-bbaa-611fffbc3254")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("f93e1261-e3b3-443d-bbaa-611fffbc3254")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("43b6a3c7-5752-4e44-acbc-4226c2829a50")]
            public virtual Ranorex.ListItem Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("43b6a3c7-5752-4e44-acbc-4226c2829a50")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("10e68b95-b254-41da-9a47-f7795a3d2b27")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("10e68b95-b254-41da-9a47-f7795a3d2b27")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("eeefab4f-f174-4d9a-a4ff-8c986fd4d76c")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("eeefab4f-f174-4d9a-a4ff-8c986fd4d76c")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The VIPCount1 item.
            /// </summary>
            [RepositoryItem("bd2622ff-ad47-4aab-b914-88cab0848f16")]
            public virtual Ranorex.Text VIPCount1
            {
                get
                {
                    return _vipcount1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount1 item info.
            /// </summary>
            [RepositoryItemInfo("bd2622ff-ad47-4aab-b914-88cab0848f16")]
            public virtual RepoItemInfo VIPCount1Info
            {
                get
                {
                    return _vipcount1Info;
                }
            }
        }

        /// <summary>
        /// The WebAppFolder folder.
        /// </summary>
        [RepositoryFolder("919c0d2e-fa35-4b4d-9ff7-f984312e6d17")]
        public partial class WebAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;

            /// <summary>
            /// Creates a new Web  folder.
            /// </summary>
            public WebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Web", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "919c0d2e-fa35-4b4d-9ff7-f984312e6d17", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 30000, null, "c6b658a6-9b55-4c40-8fb7-5ce53ef18686");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 30000, null, "bfbe8ad2-9cfc-40de-8d99-8fad44134e63");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", 30000, null, "7328d216-f1f3-4e45-af66-005beedd5b5b");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']/table//input[@name='Gender' and @type='radio' and @value='male']", 30000, null, "547aecf5-a3df-4a39-bcca-10d67beb4828");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 30000, null, "5d882631-1d19-4ca8-a64f-2243d60ae224");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 30000, null, "493678bb-cd8d-49da-acc1-39c6e582ab17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("919c0d2e-fa35-4b4d-9ff7-f984312e6d17")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("919c0d2e-fa35-4b4d-9ff7-f984312e6d17")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("c6b658a6-9b55-4c40-8fb7-5ce53ef18686")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("c6b658a6-9b55-4c40-8fb7-5ce53ef18686")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("bfbe8ad2-9cfc-40de-8d99-8fad44134e63")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("bfbe8ad2-9cfc-40de-8d99-8fad44134e63")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("7328d216-f1f3-4e45-af66-005beedd5b5b")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("7328d216-f1f3-4e45-af66-005beedd5b5b")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("547aecf5-a3df-4a39-bcca-10d67beb4828")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("547aecf5-a3df-4a39-bcca-10d67beb4828")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("5d882631-1d19-4ca8-a64f-2243d60ae224")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("5d882631-1d19-4ca8-a64f-2243d60ae224")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("493678bb-cd8d-49da-acc1-39c6e582ab17")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("493678bb-cd8d-49da-acc1-39c6e582ab17")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}